language: cpp

compiler:
 - gcc
 - clang
env:
  - BUILD_SYSTEM=gnu
  - BUILD_SYSTEM=cmake
before_script:
 - sudo apt-get install libxml2-dev
 - ./bootstrap
 - mkdir build
 - pushd build
 - cmake ..
 - popd

script:
 - if [ "$BUILD_SYSTEM" == "gnu" ]; then ./configure && make && make check; elif [ "$BUILD_SYSTEM" == "cmake" ]; then cmake --build build; fi
